# Generated by Django 2.1.3 on 2018-12-18 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories_woman',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('text', models.TextField(default='', verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='Subcategories_woman',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('number_of_copies', models.IntegerField(verbose_name='Количество экземпляров')),
                ('name_сategories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hm.Categories_woman')),
            ],
        ),
    ]
