# Generated by Django 2.1.3 on 2018-12-20 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategories_woman',
            name='price',
            field=models.IntegerField(verbose_name='Цена (сом) '),
        ),
    ]
