# Generated by Django 2.1.3 on 2018-12-21 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hm', '0002_auto_20181220_2340'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategories_woman',
            name='color',
            field=models.CharField(default='', max_length=100, verbose_name='Расцветки'),
        ),
        migrations.AddField(
            model_name='subcategories_woman',
            name='composition',
            field=models.CharField(default='', max_length=200, verbose_name='Состав'),
        ),
        migrations.AddField(
            model_name='subcategories_woman',
            name='mark',
            field=models.CharField(default='', max_length=100, verbose_name='Качество'),
        ),
        migrations.AddField(
            model_name='subcategories_woman',
            name='text',
            field=models.TextField(default='', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='subcategories_woman',
            name='price',
            field=models.IntegerField(verbose_name='Цена (сом)'),
        ),
    ]
