# Generated by Django 2.1.3 on 2018-12-21 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hm', '0003_auto_20181221_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategories_woman',
            name='mark',
            field=models.CharField(default=' ', max_length=100, verbose_name='Качество'),
        ),
    ]
