# Generated by Django 2.1.3 on 2018-12-21 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hm', '0004_auto_20181221_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategories_woman',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images', verbose_name='Картинка'),
        ),
    ]
