# Generated by Django 2.1.3 on 2018-12-21 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hm', '0005_subcategories_woman_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategories_woman',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Картинка'),
        ),
    ]
