# Generated by Django 2.1.3 on 2018-12-25 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hm', '0007_auto_20181221_2248'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategories_woman',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='images', verbose_name='Картинка(2)'),
        ),
    ]
